// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kamolas.IA - Inteligência Artificial Avançada",
  description: "Plataforma de IA mais avançada e interativa do mercado. Transforme suas ideias em realidade com Kamolas.IA",
  keywords: "inteligência artificial, IA, automação, tecnologia, inovação",
  authors: [{ name: "Kamolas.IA Team" }],
  openGraph: {
    title: "Kamolas.IA - Inteligência Artificial Avançada",
    description: "Plataforma de IA mais avançada e interativa do mercado",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}